export const THEME_CONSTANTS = {
  DISPLAY_PRODUCT_PRICE_ON_PRODUCT_LISTING_CARD: false,
  DISPLAY_ADD_CART_BUTTON_ON_PRODUCT_LISTING_CARD: false,
  DISPLAY_ADD_CATALOG_BUTTON_ON_PRODUCT_LISTING_CARD: false,
  DISPLAY_WISHLIST_ICON_ON_PRODUCT_LISTING_CARD: false,
  DISPLAY_TAG_ON_PRODUCT_LISTING_CARD: false,
  DISPLAY_WISHLIST_ICON_ON_WEB_NAVBAR: false,
  DISPLAY_WISHLIST_ICON_ON_MOB_NAVBAR: false,
  DISPLAY_CART_ON_WEB_NAVBAR: false,
  ENABLE_TOGGLE_PRODUCT_LISTING_VIEW: false,
};
